# This is a basic workflow to help you get started with Actions

name: SyncContent

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Copy Content Site-1
        run: |
          pwd
          cd ~
          mkdir site1
          cd site1
          git clone -b main https://github.com/siddhivinayak-sk/kumar.sandeep.github.io.git
          cd kumar.sandeep.github.io
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/index.md .
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/README.md .
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/_config.yml .
          git config --global user.email "siddhivinayak.sk@gmail.com"
          git config --global user.name "siddhivinayak-sk"
          git status
          git add .
          git commit -m "Changed in source"
          git push -u https://siddhivinayak-sk:${{ secrets.MY_GITHUB_TOKEN }}@github.com/siddhivinayak-sk/kumar.sandeep.github.io.git

      - name: Copy Content Site-2
        run: |
          pwd
          cd ~
          mkdir site1
          cd site1
          git clone -b main https://github.com/siddhivinayak-sk/sandeep.kumar.github.io.git
          cd sandeep.kumar.github.io
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/index.md .
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/README.md .
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/_config.yml .
          git config --global user.email "siddhivinayak.sk@gmail.com"
          git config --global user.name "siddhivinayak-sk"
          git status
          git add .
          git commit -m "Changed in source"
          git push -u https://siddhivinayak-sk:${{ secrets.MY_GITHUB_TOKEN }}@github.com/siddhivinayak-sk/sandeep.kumar.github.io.git

      - name: Copy Content Site-3
        run: |
          pwd
          cd ~
          mkdir site1
          cd site1
          git clone -b main https://github.com/siddhivinayak-sk/siddhivinayak.sk.github.io.git
          cd siddhivinayak.sk.github.io
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/index.md .
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/README.md .
          cp -rf /home/runner/work/siddhivinayak-sk.github.io/siddhivinayak-sk.github.io/_config.yml .
          git config --global user.email "siddhivinayak.sk@gmail.com"
          git config --global user.name "siddhivinayak-sk"
          git status
          git add .
          git commit -m "Changed in source"
          git push -u https://siddhivinayak-sk:${{ secrets.MY_GITHUB_TOKEN }}@github.com/siddhivinayak-sk/siddhivinayak.sk.github.io.git

